// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAil8aoK1TaTz4H8RmaWYyyYtNxVw8fQ5g',
    appId: '1:761926075595:android:26733054b489fc6276074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    storageBucket: 'eventually-user-d96c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA85vgbSsSB6DJBxin-U3IHuPBJjXyFBko',
    appId: '1:761926075595:ios:702feba9ac9af2f176074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    storageBucket: 'eventually-user-d96c2.appspot.com',
    iosClientId: '761926075595-p6oqmriqcvd9jp9ojlaten1qr0jroodh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventuallyUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA85vgbSsSB6DJBxin-U3IHuPBJjXyFBko',
    appId: '1:761926075595:ios:22d991fa7d0da61e76074e',
    messagingSenderId: '761926075595',
    projectId: 'eventually-user-d96c2',
    storageBucket: 'eventually-user-d96c2.appspot.com',
    iosClientId: '761926075595-imr2bi17un6hl735lvr1ap17vfoofcjp.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
