// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOwwS7IN_2rus4oMxwx8oZmj0UgpbBgfU',
    appId: '1:653045429731:android:098d5a25ffc4cfd938dcd6',
    messagingSenderId: '653045429731',
    projectId: 'flutter-auth-app-3ec63',
    storageBucket: 'flutter-auth-app-3ec63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC72ULnmt6LE7asUB3Mm6p03OO7IcuI1Q',
    appId: '1:653045429731:ios:260e9ae3dfde27df38dcd6',
    messagingSenderId: '653045429731',
    projectId: 'flutter-auth-app-3ec63',
    storageBucket: 'flutter-auth-app-3ec63.appspot.com',
    androidClientId: '653045429731-dt7rj32vgqjiudaao5neust8d73oqutq.apps.googleusercontent.com',
    iosClientId: '653045429731-aicbk2brfkgcqkg82utr6cc0oj7utale.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbFirebase',
  );
}
