import 'package:bakery_app/Model/bakeryItem.dart';
import 'package:bakery_app/Model/category.dart';

const Catogories = [
  Category(
    Title: 'Cakes',
    id: 'c',
  ),
  Category(
    Title: 'Donuts',
    id: 'd',
  ),
  Category(
    Title: 'Pasteries',
    id: 'p',
  ),
  Category(
    Title: 'Brownies',
    id: 'b',
  ),
];

const dummyItems = [
  BakeryItem(
    pid: '1',
    Title: 'Cakes',
    name: 'BIRTHDAY CAKE WITH GOLD ACCENTS AND WHITE AND GOLD BALLOONS',
    id: 'c',
    price: 3000,
    flavore: 'Creamy',
    desc:
        'Elevate your birthday celebration with a stunning cake adorned with elegant gold accents. This delectable masterpiece features layers of moist cake enveloped in creamy white frosting and adorned with shimmering gold details. To top it off, a bouquet of golden balloons adds a touch of magic to make the day truly unforgettable.',
    ratedStar: 5,
    image: 'assets/Images/c1.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '2',
    Title: 'Cakes',
    name: 'LYCHEE MARTINI CAKE',
    id: 'c',
    price: 2500,
    flavore: 'Creamy',
    desc:
        'Indulge in the exotic allure of a Lychee Martini Cake, blending the sweetness of lychee with a hint of martini sophistication. Layers of moist sponge cake are infused with lychee essence, while a light and creamy martini-flavored frosting adds a delightful twist. Garnished with lychee fruit and a touch of cocktail flair, this cake promises a unique and tantalizing experience for your taste buds.',
    ratedStar: 4,
    image: 'assets/Images/c2.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '3',
    Title: 'Cake',
    name: 'CHOCOLATE CAKE WITH CARAMEL DRIZZLE AND PECANS ON TOP',
    id: 'c',
    price: 2000,
    flavore: 'Chocolate',
    desc:
        'Savor the richness of a decadent chocolate cake, lavishly drizzled with luscious caramel for the ultimate indulgence. The delightful combination is crowned with a sprinkling of crunchy pecans, adding a delightful nutty texture that elevates this dessert to pure bliss. Perfect for satisfying your sweet cravings with every delightful bite.',
    ratedStar: 4,
    image: 'assets/Images/c3.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '4',
    Title: 'Cake',
    name: 'KIT KAT CAKE WITH M&M’s',
    id: 'c',
    price: 1800,
    flavore: 'Chocolate & Creamy',
    desc:
        'Indulge in a delightful Kit-Kat Cake adorned with colorful M&M\'s, a perfect fusion of crunchy and creamy. Layers of moist chocolate sponge filled with luscious frosting, enclosed by a chocolatey Kit-Kat border, and topped with a playful assortment of M&M\'s for a sweet celebration that delights both eyes and taste buds.',
    ratedStar: 4,
    image: 'assets/Images/c4.png',
    isCreamy: true,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '5',
    Title: 'Cake',
    name: 'PASTEL GREEN AND PINK FROSTING CAKE WITH CHERRIES ON TOP',
    id: 'c',
    price: 1800,
    flavore: 'Creamy',
    desc:
        'Delight in a charming pastel green and pink frosting cake, exuding a whimsical and delightful aura. Adorned with plump and juicy cherries on top, this sweet creation offers a delightful balance of flavors and colors, making it a perfect centerpiece for any celebration or occasion.',
    ratedStar: 5,
    image: 'assets/Images/c5.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '6',
    Title: 'Cake',
    name: 'PRINCESS CAKE',
    id: 'c',
    price: 1500,
    flavore: 'Creamy',
    desc:
        'Delight in a charming pastel green and pink frosting cake, exuding a whimsical and delightful aura. Adorned with plump and juicy cherries on top, this sweet creation offers a delightful balance of flavors and colors, making it a perfect centerpiece for any celebration or occasion.',
    ratedStar: 4,
    image: 'assets/Images/ca1.jpg',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '7',
    Title: 'Donut',
    name: 'CHOCOLATE COCONUT DONUT',
    id: 'd',
    price: 100,
    flavore: 'Chocolate',
    desc:
        'Indulge in the perfect fusion of rich chocolate and tropical coconut, as this delightful donut brings together the comforting flavors of cocoa and the exotic taste of shredded coconut, offering a heavenly experience in every bite.',
    ratedStar: 4,
    image: 'assets/Images/d1.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '8',
    Title: 'Donut',
    name: 'CHOCOLATE DONUT',
    id: 'd',
    price: 120,
    flavore: 'Chocolate',
    desc:
        'Experience pure chocolate bliss with this classic and irresistible chocolate donut, offering a rich cocoa flavor and a velvety texture that satisfies even the most intense chocolate cravings.',
    ratedStar: 4,
    image: 'assets/Images/d2.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '9',
    Title: 'Donut',
    name: 'GALAXY DONUT',
    id: 'd',
    price: 200,
    flavore: 'Chocolate',
    desc:
        'Embark on a cosmic journey with the Galaxy Donut, featuring mesmerizing swirls of vibrant colors and edible glitter, creating an out-of-this-world treat that\'s as visually stunning as it is delicious.',
    ratedStar: 4,
    image: 'assets/Images/d3.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '10',
    Title: 'Donut',
    name: 'KRISPY KREME WITH M&M\'S TOPPING',
    id: 'd',
    price: 250,
    flavore: 'Chocolate',
    desc:
        'Treat your taste buds to a delightful Krispy Kreme donut adorned with a colorful mosaic of M&M\'s, adding a playful crunch to the pillowy softness of the classic glazed donut, resulting in a joyful and delectable treat.',
    ratedStar: 4,
    image: 'assets/Images/d5.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '11',
    Title: 'Donut',
    name: 'SPRINKLED DONUT',
    id: 'd',
    price: 200,
    flavore: 'Chocolate',
    desc:
        'A timeless favorite, the Sprinkled Donut brings a splash of joy to any occasion, with its light and fluffy dough coated in a vibrant array of rainbow sprinkles, creating a cheerful and delightful treat.',
    ratedStar: 5,
    image: 'assets/Images/d6.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '12',
    Title: 'Donuts',
    name: 'TRES LECHES CAKE DONUT',
    id: 'd',
    price: 200,
    flavore: 'Chocolate',
    desc:
        'Enjoy a unique twist on the traditional Tres Leches cake with this sumptuous donut, soaked in a trio of milks and topped with a luscious glaze, combining the best of two beloved desserts into one delightful confection.',
    ratedStar: 4,
    image: 'assets/Images/d7.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '13',
    Title: 'Pastries',
    name: 'CHOCOLATE KITKAT PASTRY',
    id: 'p',
    price: 250,
    flavore: 'Chocolate',
    desc:
        'Experience pure chocolate bliss with the Chocolate Kitkat Pastry, where a rich chocolate mousse filling is complemented by crunchy Kitkat pieces, enclosed in a chocolate-coated pastry shell, making it a dreamy delight for chocolate enthusiasts.',
    ratedStar: 4,
    image: 'assets/Images/p1.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '14',
    Title: 'Pastries',
    name: 'CHOCOLATE PUFF PASTRY',
    id: 'p',
    price: 200,
    flavore: 'Chocolate',
    desc:
        'Delight in the lightness of a Chocolate Puff Pastry, boasting a buttery and flaky crust, filled with a rich chocolate cream, making it an elegant and airy choice for pastry aficionados.',
    ratedStar: 4,
    image: 'assets/Images/p2.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '15',
    Title: 'Pastries',
    name: 'RED VELVET PASTRY',
    id: 'p',
    price: 150,
    flavore: 'Creamy',
    desc:
        'Fall in love with the classic elegance of a Red Velvet Pastry, as its moist and tender red velvet cake layers are complemented by a sumptuous cream cheese frosting, creating a luxurious and unforgettable dessert experience.',
    ratedStar: 4,
    image: 'assets/Images/p3.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '16',
    Title: 'Pastries',
    name: 'STRAWBERRY SWIRL PASTRY',
    id: 'p',
    price: 200,
    flavore: 'Creamy',
    desc:
        'Enjoy the essence of summer in every bite with the Strawberry Swirl Pastry, featuring a delicate pastry filled with luscious strawberry cream, swirled with strawberry glaze, and garnished with fresh strawberries for a refreshing indulgence.',
    ratedStar: 5,
    image: 'assets/Images/p4.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '17',
    Title: 'Pastries',
    name: 'WHITE FOREST PASTRY',
    id: 'p',
    price: 150,
    flavore: 'Creamy',
    desc:
        'Indulge in a divine fusion of flavors with the White Forest Pastry, featuring layers of delicate white sponge cake filled with velvety white chocolate mousse, adorned with cherry compote and chocolate shavings for a luxurious treat.',
    ratedStar: 3,
    image: 'assets/Images/p5.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '18',
    Title: 'Pastries',
    name: 'BLUEBERRY CHEESE PASTRY',
    id: 'p',
    price: 200,
    flavore: 'Creamy',
    desc:
        'Delight in a delightful symphony of tastes as this pastry combines the richness of cream cheese filling with the burst of juicy blueberries, all wrapped in flaky pastry layers, creating a harmonious blend of sweet and tangy.',
    ratedStar: 4,
    image: 'assets/Images/p6.png',
    isCreamy: true,
    isChocolate: false,
  ),
  BakeryItem(
    pid: '19',
    Title: 'Brownies',
    name: 'COCOA BROWNIES',
    id: 'b',
    price: 200,
    flavore: 'Chocolate',
    desc:
        'Dive into pure chocolate indulgence with the rich and fudgy Cocoa Brownies, boasting a deep cocoa flavor and a perfect balance of chewiness and melt-in-your-mouth goodness.',
    ratedStar: 5,
    image: 'assets/Images/b1.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '20',
    Title: 'Brownies',
    name: 'COSMIC BROWNIES',
    id: 'b',
    price: 150,
    flavore: 'Chocolate',
    desc:
        'Embark on a cosmic journey of taste with Cosmic Brownies, featuring a nostalgic blend of fudgy chocolate, colorful candy-coated chocolate pieces, and a soft, chewy texture that brings back childhood memories in every bite.',
    ratedStar: 5,
    image: 'assets/Images/b2.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '21',
    Title: 'Brownies',
    name: 'SALTED CARAMEL BROWNIES',
    id: 'b',
    price: 250,
    flavore: 'Chocolate',
    desc:
        'Experience the sweet-savory delight of Salted Caramel Brownies, featuring gooey caramel swirls over a velvety chocolate base, enhanced with a sprinkle of sea salt for an irresistible contrast of flavors.',
    ratedStar: 4,
    image: 'assets/Images/b3.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '22',
    Title: 'Brownies',
    name: 'PEPPERMINT BARK',
    id: 'b',
    price: 300,
    flavore: 'Chocolate',
    desc:
        'Indulge in the delightful combination of rich chocolate brownie topped with a luscious layer of peppermint bark, offering a festive and refreshing twist to the classic treat. The decadent cocoa flavors blend harmoniously with the cool, minty goodness, creating a mouthwatering sensation that\'s perfect for any holiday or special occasion.',
    ratedStar: 4,
    image: 'assets/Images/b4.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '23',
    Title: 'Brownies',
    name: 'SPRINKLE BROWNIE POPSICLES',
    id: 'b',
    price: 300,
    flavore: 'Chocolate',
    desc:
        'Delight in a whimsical treat with Sprinkle Brownie Popsicles, combining the fun of sprinkles with the convenience of a handheld treat, perfect for any celebration or on-the-go enjoyment.',
    ratedStar: 5,
    image: 'assets/Images/b5.png',
    isCreamy: false,
    isChocolate: true,
  ),
  BakeryItem(
    pid: '24',
    Title: 'Brownies',
    name: 'WHITE BROWNIES',
    id: 'b',
    price: 200,
    flavore: 'Vanilla',
    desc:
        'Discover a unique twist on the classic with White Brownies, as these blondies offer a buttery, vanilla-infused goodness, delivering a delightful change of pace for those seeking a lighter alternative.',
    ratedStar: 3,
    image: 'assets/Images/b6.png',
    isCreamy: false,
    isChocolate: false,
  ),
];
