name: real_deal
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  get: ^4.6.5
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  cart_stepper: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
  #       - asset: assets/fonts/static/Inter-Thin.ttf
  #       - asset: assets/fonts/static/Inter-Black.ttf
  #       - asset: assets/fonts/static/Inter-Light.ttf
  #       - asset: assets/fonts/static/Inter-ExtraLight.ttf
  #       - asset: assets/fonts/static/Inter-Regular.ttf
  #       - asset: assets/fonts/static/Inter-Medium.ttf
  #       - asset: assets/fonts/static/Inter-Bold.ttf
  #       - asset: assets/fonts/static/Inter-ExtraBold.ttf
  #       - asset: assets/fonts/static/Inter-SemiBold.ttf
  #   - family: MontserratAlternates
  #     fonts:
  #       - asset: assets/fonts/MontserratAlternates-Black.ttf
  #       - asset: assets/fonts/MontserratAlternates-Regular.ttf
  #       - asset: assets/fonts/MontserratAlternates-BlackItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-Bold.ttf
  #       - asset: assets/fonts/MontserratAlternates-BoldItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-ExtraBold.ttf
  #       - asset: assets/fonts/MontserratAlternates-ExtraBoldItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-ExtraLight.ttf
  #       - asset: assets/fonts/MontserratAlternates-ExtraLightItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-Italic.ttf
  #       - asset: assets/fonts/MontserratAlternates-Light.ttf
  #       - asset: assets/fonts/MontserratAlternates-LightItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-Medium.ttf
  #       - asset: assets/fonts/MontserratAlternates-MediumItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-SemiBold.ttf
  #       - asset: assets/fonts/MontserratAlternates-SemiBoldItalic.ttf
  #       - asset: assets/fonts/MontserratAlternates-Thin.ttf
  #       - asset: assets/fonts/MontserratAlternates-ThinItalic.ttf